### ISSUE TITLE
Issues with ABC (US American Broadcast - go.py)

### ISSUE THREAD

**Issue by kucksdorfs** [blackjack4494/youtube-dlc#113]
## Checklist

- [X] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dlc version **2020.09.14**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://abc.com/shows/the-rookie/episode-guide/season-02/18-under-the-gun', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.09.13
[debug] Python version 3.8.5 (CPython) - Linux-5.4.64-1-lts-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[Go] 18-under-the-gun: Downloading webpage
[Go] VDKA4974899: Downloading JSON metadata
[debug] Using fake IP 6.132.216.190 (US) as X-Forwarded-For.
[Go] VDKA4974899: Downloading JSON metadata
ERROR: Go said: 1025:Unable to retrieve required files for playback. Please try again in a few minutes.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 798, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dlc/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dlc/extractor/go.py", line 205, in _real_extract
    raise ExtractorError('%s said: %s' % (self.IE_NAME, error_message), expected=True)
youtube_dlc.utils.ExtractorError: Go said: 1025:Unable to retrieve required files for playback. Please try again in a few minutes.
```

## Description

I know I didn't mark that I had the latest (my version is 2020.09.13 and PIP doesn't have any newer version), but I have verified that the pull request linked below fixes the issue. I am not sure what the rules are for contribution when I didn't write the code, but copied/pasted from another project.

https://github.com/ytdl-org/youtube-dl/pull/25216

**Comment by kucksdorfs** [comment]
I am checking the "I've verified I am using the latest" because it appears the latest is the version I have installed.

**Comment by jsmith1299** [comment]
I have the same issue as well with version 9.20. Tried a few ways as well.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://abc.com/shows/united-we-fall/episode-guide/season-01/08-rewedding-crashers', '--no-cache-dir', '--ap-mso', 'Verizon', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93302-g147ef1d947, ffprobe N-93302-g147ef1d947


D:\TV Series\United we Fall>youtube-dl.exe https://abc.com/shows/united-we-fall/episode-guide/season-01/08-rewedding-crashers --no-cache-dir -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://abc.com/shows/united-we-fall/episode-guide/season-01/08-rewedding-crashers', '--no-cache-dir', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-93302-g147ef1d947, ffprobe N-93302-g147ef1d947
[debug] Proxy map: {}
[Go] 08-rewedding-crashers: Downloading webpage
[Go] VDKA4974899: Downloading JSON metadata
[debug] Using fake IP 6.20.65.122 (US) as X-Forwarded-For.
[Go] VDKA4974899: Downloading JSON metadata
ERROR: Go said: 1025:Unable to retrieve required files for playback. Please try again in a few minutes.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\go.py", line 205, in _real_extract
youtube_dl.utils.ExtractorError: Go said: 1025:Unable to retrieve required files for playback. Please try again in a few minutes.
[debug] Proxy map: {}
[Go] 08-rewedding-crashers: Downloading webpage
[Go] VDKA4974899: Downloading JSON metadata
[debug] Using fake IP 6.198.183.162 (US) as X-Forwarded-For.
[Go] VDKA4974899: Downloading JSON metadata
ERROR: Go said: 1025:Unable to retrieve required files for playback. Please try again in a few minutes.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\go.py", line 205, in _real_extract
youtube_dl.utils.ExtractorError: Go said: 1025:Unable to retrieve required files for playback. Please try again in a few minutes.

**Comment by kucksdorfs** [comment]
So... since no one has actually answered my question, I will copy the PR from youtube-dl that fixes this and submit it to this repo.
