### ISSUE TITLE
[mitele] not working again

### ISSUE THREAD

**Issue by felisucoibi** [blackjack4494/youtube-dlc#117]
- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dlc version **2020.09.14**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

example of url
https://www.mitele.es/tv-movies/cuidado-amiga-41_1008571090001/player/

youtube-dlc https://www.mitele.es/tv-movies/cuidado-amiga-41_1008571090001/player/
[MiTele] cuidado-amiga-41_1008571090001: Downloading webpage
[Ooyala] 281b8025-7455-47e3-b92d-6ebeaec03172: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dlc/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dlc/youtube_dlc/__init__.py", line 475, in main
  File "/usr/local/bin/youtube-dlc/youtube_dlc/__init__.py", line 465, in _real_main
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 2041, in download
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 809, in extract_info
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 876, in process_ie_result
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 798, in extract_info
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/ooyala.py", line 173, in _real_extract
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/ooyala.py", line 28, in _extract
IndexError: list index out of range

**Comment by blackjack4494** [comment]
The mitele fix https://github.com/blackjack4494/youtube-dlc/pull/109 isn't released yet.  
A new release should be coming today.  
However it the fix should work (don't mind the 403 error since I am getting geoblocked)

> PS D:\gitkraken\youtube-dl> python3 -m youtube_dlc "https://www.mitele.es/tv-movies/cuidado-amiga-41_1008571090001/player/" -v -F
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.mitele.es/tv-movies/cuidado-amiga-41_1008571090001/player/', '-v', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.14
[debug] Git HEAD: 78895bd3a
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[MiTele] cuidado-amiga-41_1008571090001: Downloading webpage
[MiTele] 281b8025-7455-47e3-b92d-6ebeaec03172: Downloading config JSON
[MiTele] 281b8025-7455-47e3-b92d-6ebeaec03172: Downloading gbx JSON
[MiTele] 281b8025-7455-47e3-b92d-6ebeaec03172: Downloading caronte JSON
[MiTele] 281b8025-7455-47e3-b92d-6ebeaec03172: Downloading cerbero JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

**Comment by blackjack4494** [comment]
@felisucoibi will close for now. Try the updated version.

**Comment by felisucoibi** [comment]
Using version 2020.09.14 it does not work
I used youdube-dlc -U

[MiTele] cuidado-amiga-41_1008571090001: Downloading webpage
[Ooyala] 281b8025-7455-47e3-b92d-6ebeaec03172: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dlc/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dlc/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dlc/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dlc/youtube_dl/YoutubeDL.py", line 2019, in download
  File "/usr/local/bin/youtube-dlc/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "/usr/local/bin/youtube-dlc/youtube_dl/YoutubeDL.py", line 875, in process_ie_result
  File "/usr/local/bin/youtube-dlc/youtube_dl/YoutubeDL.py", line 797, in extract_info
  File "/usr/local/bin/youtube-dlc/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dlc/youtube_dl/extractor/ooyala.py", line 173, in _real_extract
  File "/usr/local/bin/youtube-dlc/youtube_dl/extractor/ooyala.py", line 28, in _extract
IndexError: list index out of range

**Comment by felisucoibi** [comment]
Sorry true its working with 2020.09.16 thanks a alot

**Comment by blackjack4494** [comment]
You may want to install Python 3 (3.8. is newest). 2.7 will be end of life at January 1st 2020.
