### ISSUE TITLE
[BitChute] For a working video: video URL is invalid/no video formats found

### ISSUE THREAD

**Issue by jbruchon** [blackjack4494/youtube-dlc#121]
## Verbose log
```
youtube-dl --cookies "Y:\cookies.txt" --add-metadata --write-description --write-info-json --write-thumbnail --download-archive "Y:\ytdl_archive.txt" --all-subs --sleep-interval 1 -ciw -o "%(title)s.%(ext)s" -v https://www.bitchute.com/video/koRP1rj8pkk/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'Y:\\cookies.txt', '--add-metadata', '--write-description', '--write-info-json', '--write-thumbnail', '--download-archive', 'Y:\\ytdl_archive.txt', '--all-subs', '--sleep-interval', '1', '-ciw', '-o', '%(title)s.%(ext)s', '-v', 'https://www.bitchute.com/video/koRP1rj8pkk/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.16
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-04-15-51db0a4, ffprobe N-92179-gc27c7b49dc
[debug] Proxy map: {}
[BitChute] koRP1rj8pkk: Downloading webpage
[BitChute] koRP1rj8pkk: Checking video URL
[BitChute] koRP1rj8pkk: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 798, in extract_info
  File "youtube_dlc\extractor\common.py", line 530, in extract
  File "youtube_dlc\extractor\bitchute.py", line 74, in _real_extract
  File "youtube_dlc\extractor\common.py", line 1350, in _sort_formats
youtube_dlc.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

Valid BitChute video URL fails to extract any videos. Confirmed that video at that URL works in Firefox.

**Comment by blackjack4494** [comment]
The video you used won't even play in my browsers. The linked media file is not responding (tested on home connection and vpn usa/netherlands). However a random video like this https://www.bitchute.com/video/5WBwp1lKNuSW/ works toally fine.

> [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.bitchute.com/video/5WBwp1lKNuSW/', '-v', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.16
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[BitChute] 5WBwp1lKNuSW: Downloading webpage
[BitChute] 5WBwp1lKNuSW: Checking video URL
[info] Available formats for 5WBwp1lKNuSW:
format code  extension  resolution note
0            mp4        unknown
