### ISSUE TITLE
[Broken] Sonlyliv.com is broken

### ISSUE THREAD

**Issue by Ashish0804** [blackjack4494/youtube-dlc#135]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.09.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.sonyliv.com/shows/sankatmochan-mahabali-hanuman-1700000109/luv-kush-find-ashwamedha-1000022211']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.06
[debug] Python version 3.7.7 (CPython) - Linux-5.4.0-7642-generic-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] luv-kush-find-ashwamedha-1000022211: Requesting header
WARNING: Falling back on generic information extractor.
[generic] luv-kush-find-ashwamedha-1000022211: Downloading webpage
[generic] luv-kush-find-ashwamedha-1000022211: Extracting information
WARNING: [generic] luv-kush-find-ashwamedha-1000022211: Failed to parse JSON Extra data: line 15 column 19 (char 691)
ERROR: Unsupported URL: https://www.sonyliv.com/shows/sankatmochan-mahabali-hanuman-1700000109/luv-kush-find-ashwamedha-1000022211
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.sonyliv.com/shows/sankatmochan-mahabali-hanuman-1700000109/luv-kush-find-ashwamedha-1000022211


```

## Description

@blackjack4494 this seems to be a regex error too, can u please take a look at it. 
Thanks

P.S.: use a vpn

**Comment by blackjack4494** [comment]
You might be right. 
What country is needed to visit this site?

**Comment by Ashish0804** [comment]
> You might be right.
> What country is needed to visit this site?
> I will see if my internet is fixed again later or whether I still have issues.

This works in INDIA.

**Comment by blackjack4494** [comment]
You were right. It's a regex error. They changed the url pattern.

**Comment by Ashish0804** [comment]
> You were right. It's a regex error. They changed the url pattern.
> However I do not know yet what id they expect or need.
> I believe it's just the really last part with digits. But I guess my VPN is having issues right now.

Yes i guess u are right about the id

> https://www.sonyliv.com/shows/sankatmochan-mahabali-hanuman-1700000109/luv-kush-find-ashwamedha-1000022211

this link needs to match 

> 1000022211

If you are not able to login to the vpn, then let me know, i can provide a new one.

Thanks

**Comment by Ashish0804** [comment]
@blackjack4494 m8 while is the vpn is still working, can u pls take a look at this too?

Thanks a lot :)

**Comment by theincognito-inc** [comment]
@Ashish0804 

They are using different url structure for different stuff.
For shows and sports:
sonyliv.com/shows/showname-10x/episodename-10x
sonyliv.com/sports/showname-10x/episodename-10x

But for movies:
sonyliv.com/movies/moviename-10x

where 10x => 10 digit number


Hotstar has an easier implementation, where hotstar.com/videoid will redirect to the appropriate video, irrespective of the content category. I am not good with regex in particular, so hopefully @blackjack4494 can use this info and try an appropriate regex. I will try myself in the meantime.

**Comment by FaArIsH** [comment]
i think sonyliv and zee5 almost all videos are drm protected now

**Comment by theincognito-inc** [comment]
> 
> 
> i think sonyliv and zee5 almost all videos are drm protected now

Yeah, they are using DRM even for free to play videos.
