### ISSUE TITLE
[Broken] All BitChute downloads fail

### ISSUE THREAD

**Issue by jbruchon** [blackjack4494/youtube-dlc#153]
BitChute is failing for me in 100% of cases after upgrading to the last released executable version.

(Also, you may want to change the support URL in the error text to not point at yt-dl.org for bug reports.)

```
[download] Downloading video 553 of 572
[BitChute] 5aikabinZFTg: Downloading webpage
[BitChute] 5aikabinZFTg: Checking video URL
[BitChute] 5aikabinZFTg: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 819, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\bitchute.py", line 74, in _real_extract
  File "youtube_dlc\extractor\common.py", line 1359, in _sort_formats
youtube_dlc.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

[download] Downloading video 554 of 572
[BitChute] f6ckTWH-I8k: Downloading webpage
[BitChute] f6ckTWH-I8k: Checking video URL
[BitChute] f6ckTWH-I8k: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 819, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\bitchute.py", line 74, in _real_extract
  File "youtube_dlc\extractor\common.py", line 1359, in _sort_formats
youtube_dlc.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

**Comment by blackjack4494** [comment]
It's working. Your videos are the problem.

**Comment by jbruchon** [comment]
Sorry. Apparently BitChute has this problem far more than I realized. It has happened for several different channels now; that one just happens to have had several hundred failures, so I noticed it.
