### ISSUE TITLE
[Broken] amcnetworks - Unable to extract media url

### ISSUE THREAD

**Issue by StevenDTX** [blackjack4494/youtube-dlc#180]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dlc version **2020.09.16**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
U:\>c:\support\youtube-dlc.exe --verbose https://www.amc.com/shows/the-salisbury-poisonings/episodes/season-1-the-salisbury-poisonings-episode-1--48143
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.amc.com/shows/the-salisbury-poisonings/episodes/season-1-the-salisbury-poisonings-episode-1--48143']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.10.09
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-92986-gaceb9131c1, ffprobe N-92986-gaceb9131c1
[debug] Proxy map: {}
[AMCNetworks] season-1-the-salisbury-poisonings-episode-1--48143: Downloading webpage
ERROR: Unable to extract media url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 830, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\amcnetworks.py", line 66, in _real_extract
  File "youtube_dlc\extractor\common.py", line 1010, in _search_regex
youtube_dlc.utils.RegexNotFoundError: Unable to extract media url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.


```
```
U:\>c:\support\youtube-dlc.exe --verbose https://www.wetv.com/shows/life-after-lockup/episodes/season-3-threes-a-crowd--48289
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.wetv.com/shows/life-after-lockup/episodes/season-3-threes-a-crowd--48289']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.10.09
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-92986-gaceb9131c1, ffprobe N-92986-gaceb9131c1
[debug] Proxy map: {}
[AMCNetworks] season-3-threes-a-crowd--48289: Downloading webpage
ERROR: Unable to extract media url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 830, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\amcnetworks.py", line 66, in _real_extract
  File "youtube_dlc\extractor\common.py", line 1010, in _search_regex
youtube_dlc.utils.RegexNotFoundError: Unable to extract media url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

Unable to extract media url.

**Comment by october262** [comment]
the first time i tried this link - https://www.amc.com/shows/the-salisbury-poisonings/episodes/season-1-the-salisbury-poisonings-episode-1--48143 with the Firefox addon called the stream detector, it got the m3u8 files. closed the tab and reopened the tab to attempt  to download the episode it  now says it has DRM protection.

**Comment by blackjack4494** [comment]
Cannot really test anything here. Need a vpn for that.
There are also non drm files available it seems  
https://amc350885sec-a.akamaihd.net/thumbnail/AMC_Networks/1012/663/pre_start_preferred_formats__v1_0_2.min.js

**Comment by october262** [comment]
i was able to download & playback this episode just fine  https://www.amc.com/shows/the-salisbury-poisonings/episodes/season-1-the-salisbury-poisonings-episode-1--48143

this episode - https://www.wetv.com/shows/life-after-lockup/episodes/season-3-threes-a-crowd--48289 requires a tv provider

**Comment by StevenDTX** [comment]
These appear to be free and available (as of post time).  

https://www.amc.com/shows/fear-the-walking-dead/episodes/season-6-the-end-is-the-beginning--48698

https://www.wetv.com/shows/love-after-lockup/episodes/season-3-2-put-a-sweater-on-and-chill--48584

Yes, I too, can get the m3u8 in the browser, but thats not as easily automated.

**Comment by StevenDTX** [comment]
> 
> 
> Cannot really test anything here. Need a vpn for that.
> There are also non drm files available it seems
> https://amc350885sec-a.akamaihd.net/thumbnail/AMC_Networks/1012/663/pre_start_preferred_formats__v1_0_2.min.js

Is there some output I can get for you?  I am in the US and have a subscription.
