### ISSUE TITLE
age restricted video

### ISSUE THREAD

**Issue by october262** [blackjack4494/youtube-dlc#192]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dlc version **2020.09.14**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```bowser@bowser-Inspiron-530:~$ youtube-dlc https://www.youtube.com/watch?v=sBzrzS1Ag_g
[youtube] sBzrzS1Ag_g: Downloading webpage
[youtube] sBzrzS1Ag_g: Downloading embed webpage
ERROR: Video is age restricted and only playable on Youtube. Requires cookies!
bowser@bowser-Inspiron-530:~$ youtube-dlc https://www.youtube.com/watch?v=sBzrzS1Ag_g -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=sBzrzS1Ag_g', u'-v']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.09
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-121-generic-i686-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] sBzrzS1Ag_g: Downloading webpage
[youtube] sBzrzS1Ag_g: Downloading embed webpage
ERROR: Video is age restricted and only playable on Youtube. Requires cookies!
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/youtube.py", line 1902, in _real_extract
    raise ExtractorError('Video is age restricted and only playable on Youtube. Requires cookies!', expected=True)
ExtractorError: Video is age restricted and only playable on Youtube. Requires cookies!

bowser@bowser-Inspiron-530:~$ 

PASTE VERBOSE LOG HERE
```

## Description

!--age restricted video not working for this video  - https://www.youtube.com/watch?v=XgnwCQzjau8  and this video https://www.youtube.com/watch?v=sBzrzS1Ag_g   using youtube-dlc version 10 -9 -2020  tried signed in / not signed in and with and without cookies

**Comment by october262** [comment]
update !! this video  -  https://www.youtube.com/watch?v=sBzrzS1Ag_g  does work
without being signed in & using cookies using just youtube-dl
this video -

**Comment by nicolaasjan** [comment]
> this video - https://www.youtube.com/watch?v=XgnwCQzjau8 does not work with either
> youtube-dl or youtube-dlc

Just made a fresh `cookies.txt` file and it worked here.

Verbose log:

```
youtube-dlc -v https://www.youtube.com/watch?v=XgnwCQzjau8
[debug] System config: []
[debug] User config: ['-o', '/dev/shm/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--no-mtime', '--add-metadata', '--embed-thumbnail', '--cookies', '/home/nico/.config/youtube-dl/cookies.txt']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=XgnwCQzjau8']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.09
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-121-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg N-99430-g9d8f9b2-Nico_20201001, ffprobe N-99430-g9d8f9b2-Nico_20201001
[debug] Proxy map: {}
[youtube] XgnwCQzjau8: Downloading webpage
[youtube] XgnwCQzjau8: Downloading embed webpage
[youtube] XgnwCQzjau8: Downloading MPD manifest
[youtube] XgnwCQzjau8: Downloading thumbnail ...
[youtube] XgnwCQzjau8: Writing thumbnail to: /dev/shm/youtube-dl - --cookies option.webp
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1602888504/ei/2M6JX_P_Lqr5sAKc5oQI/ip/#REDACTED#/id/5e09f0090ce36aef/source/youtube/requiressl/yes/playback_host/r3---sn-5hne6nsd.googlevideo.com/mh/zu/mm/31%2C26/mn/sn-5hne6nsd%2Csn-4g5ednsl/ms/au%2Conr/mv/m/mvi/3/pl/15/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/2200000/vprv/1/mt/1602866807/fvip/3/keepalive/yes/fexp/23915654/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIhAIqTsFEj61V-WXJRHXwnewW_kqma3J6V-5HI77u9NcfMAiARyqDxTGdedZBevDvt4ejvCgzrdmBTFVmyA0RgSUPlSw%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgCQ41N9kMdekaiN-iFkIA4gMe4rpWSroBb9ji2jmeRkgCIQCN4aMy6njksZktYerYHlEXVUOGTNVAeb16dokoDwtSvA%3D%3D'
[dashsegments] Total fragments: 130
[download] Destination: /dev/shm/youtube-dl - --cookies option.f136.mp4
[download] 100% of 39.30MiB in 00:13
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1602888504/ei/2M6JX_P_Lqr5sAKc5oQI/ip/#REDACTED#/id/5e09f0090ce36aef/source/youtube/requiressl/yes/playback_host/r3---sn-5hne6nsd.googlevideo.com/mh/zu/mm/31%2C26/mn/sn-5hne6nsd%2Csn-4g5ednsl/ms/au%2Conr/mv/m/mvi/3/pl/15/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/2200000/vprv/1/mt/1602866807/fvip/3/keepalive/yes/fexp/23915654/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIhAIqTsFEj61V-WXJRHXwnewW_kqma3J6V-5HI77u9NcfMAiARyqDxTGdedZBevDvt4ejvCgzrdmBTFVmyA0RgSUPlSw%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgCQ41N9kMdekaiN-iFkIA4gMe4rpWSroBb9ji2jmeRkgCIQCN4aMy6njksZktYerYHlEXVUOGTNVAeb16dokoDwtSvA%3D%3D'
[dashsegments] Total fragments: 70
[download] Destination: /dev/shm/youtube-dl - --cookies option.f140.m4a
[download] 100% of 10.57MiB in 00:09
[ffmpeg] Merging formats into "/dev/shm/youtube-dl - --cookies option.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/dev/shm/youtube-dl - --cookies option.f136.mp4' -i 'file:/dev/shm/youtube-dl - --cookies option.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:/dev/shm/youtube-dl - --cookies option.temp.mp4'
Deleting original file /dev/shm/youtube-dl - --cookies option.f140.m4a (pass -k to keep)
Deleting original file /dev/shm/youtube-dl - --cookies option.f136.mp4 (pass -k to keep)
[ffmpeg] Adding metadata to '/dev/shm/youtube-dl - --cookies option.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/dev/shm/youtube-dl - --cookies option.mp4' -map 0 -c copy -metadata 'title=youtube-dl: --cookies option' -metadata date=20200324 -metadata 'description=youtube-dl: --cookies option


Some YouTube videos can be downloaded or streamed only if the user is logged and is over 18 years old.
In the case of the youtube-dl utility, the --cookies option must be used, because the --username and --password options are not accepted by YouTube.


Disclaimer: This episode is neither a promotion nor a recommendation any product or service, but does reflect my personal experiences.
Disclaimer: This episode is presented with ABSOLUTELY NO WARRANTY WHATSOEVER.
Remember: you are listening to an idiot running his mouth.


Date:  24 MARCH 2020

[obs q6 ffmpeg irfanview]' -metadata 'comment=youtube-dl: --cookies option


Some YouTube videos can be downloaded or streamed only if the user is logged and is over 18 years old.
In the case of the youtube-dl utility, the --cookies option must be used, because the --username and --password options are not accepted by YouTube.


Disclaimer: This episode is neither a promotion nor a recommendation any product or service, but does reflect my personal experiences.
Disclaimer: This episode is presented with ABSOLUTELY NO WARRANTY WHATSOEVER.
Remember: you are listening to an idiot running his mouth.


Date:  24 MARCH 2020

[obs q6 ffmpeg irfanview]' -metadata 'purl=https://www.youtube.com/watch?v=XgnwCQzjau8' -metadata artist=SteveAB4EL 'file:/dev/shm/youtube-dl - --cookies option.temp.mp4'
[ffmpeg] Converting thumbnail "/dev/shm/youtube-dl - --cookies option.webp" to JPEG
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/dev/shm/youtube-dl - --cookies option.webp' -bsf:v mjpeg2jpeg 'file:/dev/shm/youtube-dl - --cookies option.jpg'
[atomicparsley] Adding thumbnail to "/dev/shm/youtube-dl - --cookies option.mp4"
[debug] AtomicParsley command line: AtomicParsley '/dev/shm/youtube-dl - --cookies option.mp4' --artwork '/dev/shm/youtube-dl - --cookies option.jpg' -o '/dev/shm/youtube-dl - --cookies option.temp.mp4'
```

**Comment by october262** [comment]
SOLVED !! had to run like this - bowser@bowser-Inspiron-530:~$ python3 /usr/local/bin/youtube-dlc https://www.youtube.com/watch?v=sBzrzS1Ag_g --cookies '/home/bowser/Downloads/cookies.txt' -f mp4  it works.

**Comment by blackjack4494** [comment]
For some reason you sometimes need very fresh cookies but not always.

**Comment by nicolaasjan** [comment]
> SOLVED !! had to run like this - bowser@bowser-Inspiron-530:~$ python3 /usr/local/bin/youtube-dlc [Tame Impala - The Less I Know The Better (Official Video)](https://www.youtube.com/watch?v=sBzrzS1Ag_g) --cookies '/home/bowser/Downloads/cookies.txt' -f mp4 it works. both link now work

Yeah...,

That's why I use an alias for the youtube-dlc command:
`alias youtube-dlc='python3 /usr/local/bin/youtube-dlc'`

Insert that line in the file `.bash_aliases` in your `/home` folder.
If it doesn't exist, create it.
It's a hidden file; to view hidden files, press `Ctrl+H`.
