### ISSUE TITLE
[Broken] YouTube stream trigger "ERROR: 'url'"

### ISSUE THREAD

**Issue by TheFrenchGhosty** [blackjack4494/youtube-dlc#198]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.09**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--format', '(bestvideo[vcodec^=avc1][height=1080][fps>30]/bestvideo[vcodec^=avc1][height=1080]/bestvideo[vcodec^=avc1][height=720][fps>30]/bestvideo[vcodec^=avc1][height=720]/bestvideo[vcodec^=avc1])+(bestaudio[acodec^=mp4a]/bestaudio)/best', '--verbose', '--force-ipv4', '--sleep-interval', '5', '--max-sleep-interval', '30', '--ignore-errors', '--no-continue', '--no-overwrites', '--download-archive', 'archive.log', '--add-metadata', '--all-subs', '--sub-format', 'srt', '--embed-subs', '--output', '%(uploader)s - %(upload_date)s - %(title)s [%(id)s].%(ext)s', '--merge-output-format', 'mkv', '--batch-file', 'Source - Watch on Mobile Devices.txt']
[debug] Batch file urls: ['https://invidious.snopyta.org/watch?v=8gEfHD_y7Pc']
[debug] Loading archive file 'archive.log'
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.10.09
[debug] Python version 3.8.5 (CPython) - Linux-5.4.59-1-lts-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 8gEfHD_y7Pc: Downloading webpage
WARNING: No subtitle format found matching "srt" for language live_chat, using json
[info] Writing video subtitles to: Linus Tech Tips - 20201016 - NVIDIA Surrenders! Founder's Edition RTX Cards De-listed - WAN Show October 16 , 2020 [8gEfHD_y7Pc].live_chat.json
ERROR: 'url'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 841, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 896, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1691, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1893, in process_info
    sub_info['url'], info_dict['id'], note=False).read()
KeyError: 'url'

```

## Description

Running a modified version of [my script](https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/blob/master/Linux%20-%20OSX/Watch%20on%20Mobile%20Devices%20Script/Watch%20on%20Mobile%20Devices.sh) that use youtube-dlc instead of youtube-dl.

URL that trigger this issue: https://invidious.snopyta.org/watch?v=8gEfHD_y7Pc

**Comment by blackjack4494** [comment]
Likely related to #163 which I am still trying to find a good patch for it but made some progress on it already.

**Comment by TheFrenchGhosty** [comment]
@blackjack4494 It indeed looks like the same problem
