### ISSUE TITLE
[Broken]

### ISSUE THREAD

**Issue by wsaribeiro** [blackjack4494/youtube-dlc#208]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dlc version **2020.10.09**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', 'https://cursos.alura.com.br/course/mysql-manipule-dados-com-sql/']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.10.09
[debug] Python version 3.7.8 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[AluraCourse] Downloading login popup
[AluraCourse] Logging in
[AluraCourse] mysql-manipule-dados-com-sql: Downloading webpage
[AluraCourse] mysql-manipule-dados-com-sql: Downloading webpage
[AluraCourse] mysql-manipule-dados-com-sql: Downloading webpage
[AluraCourse] mysql-manipule-dados-com-sql: Downloading webpage
[AluraCourse] mysql-manipule-dados-com-sql: Downloading webpage
[AluraCourse] mysql-manipule-dados-com-sql: Downloading webpage
[download] Downloading playlist: mysql-manipule-dados-com-sql
[AluraCourse] playlist mysql-manipule-dados-com-sql: Collected 26 video ids (downloading 26 of them)
[download] Downloading video 1 of 26
[Alura] Downloading login popup
[Alura] 54321: Searching for videos
[Alura] 54321: Downloading webpage
[Alura] Downloading m3u8 information
Traceback (most recent call last):
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wsari\AppData\Local\Programs\Python\Python37\Scripts\youtube-dlc.exe\__main__.py", line 7, in <module>
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\__init__.py", line 487, in main
    _real_main(argv)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\__init__.py", line 477, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\YoutubeDL.py", line 2096, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\YoutubeDL.py", line 841, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\YoutubeDL.py", line 1041, in process_ie_result
    extra_info=extra)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\YoutubeDL.py", line 908, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\extractor\alura.py", line 62, in _real_extract
    m3u8_id='hls', fatal=False)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\extractor\common.py", line 1637, in _extract_m3u8_formats
    preference=preference, m3u8_id=m3u8_id, live=live)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\extractor\common.py", line 1755, in _parse_m3u8_formats
    manifest_url = format_url(line.strip())
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\extractor\common.py", line 1653, in <lambda>
    else compat_urlparse.urljoin(m3u8_url, u))
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\urllib\parse.py", line 511, in urljoin
    urlparse(url, bscheme, allow_fragments)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\urllib\parse.py", line 368, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\urllib\parse.py", line 459, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

## Description

URL that trigger this issue:
https://cursos.alura.com.br/course/mysql-manipule-dados-com-sql/

**Comment by blackjack4494** [comment]
`-4` to your command line.

**Comment by wsaribeiro** [comment]
same return.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--force-ipv4', '--verbose', 'https://cursos.alura.com.br/course/mysql-manipule-dados-com-sql/']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.10.09
[debug] Python version 3.7.8 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[AluraCourse] Downloading login popup
[AluraCourse] Logging in
[AluraCourse] mysql-manipule-dados-com-sql: Downloading webpage
[AluraCourse] mysql-manipule-dados-com-sql: Downloading webpage
[AluraCourse] mysql-manipule-dados-com-sql: Downloading webpage
[AluraCourse] mysql-manipule-dados-com-sql: Downloading webpage
[AluraCourse] mysql-manipule-dados-com-sql: Downloading webpage
[AluraCourse] mysql-manipule-dados-com-sql: Downloading webpage
[download] Downloading playlist: mysql-manipule-dados-com-sql
[AluraCourse] playlist mysql-manipule-dados-com-sql: Collected 26 video ids (downloading 26 of them)
[download] Downloading video 1 of 26
[Alura] Downloading login popup
[Alura] 54321: Searching for videos
[Alura] 54321: Downloading webpage
[Alura] Downloading m3u8 information
Traceback (most recent call last):
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wsari\AppData\Local\Programs\Python\Python37\Scripts\youtube-dlc.exe\__main__.py", line 7, in <module>
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\__init__.py", line 487, in main
    _real_main(argv)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\__init__.py", line 477, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\YoutubeDL.py", line 2096, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\YoutubeDL.py", line 841, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\YoutubeDL.py", line 1041, in process_ie_result
    extra_info=extra)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\YoutubeDL.py", line 908, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\extractor\alura.py", line 62, in _real_extract
    m3u8_id='hls', fatal=False)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\extractor\common.py", line 1637, in _extract_m3u8_formats
    preference=preference, m3u8_id=m3u8_id, live=live)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\extractor\common.py", line 1755, in _parse_m3u8_formats
    manifest_url = format_url(line.strip())
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\site-packages\youtube_dlc\extractor\common.py", line 1653, in <lambda>
    else compat_urlparse.urljoin(m3u8_url, u))
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\urllib\parse.py", line 511, in urljoin
    urlparse(url, bscheme, allow_fragments)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\urllib\parse.py", line 368, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "c:\users\wsari\appdata\local\programs\python\python37\lib\urllib\parse.py", line 459, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

**Comment by blackjack4494** [comment]
@hugohaa may be able to help,

**Comment by wsaribeiro** [comment]
if I use **--force-generic-extractor**, works, but downloads only first video.
