### ISSUE TITLE
[Broken] [nickelodeon] ERROR: Conversion failed!

### ISSUE THREAD

**Issue by hazcod** [blackjack4494/youtube-dlc#219]
## Checklist

- [ X] I'm reporting a broken site support
- [X ] I've verified that I'm running youtube-dlc version **2020.11.11-3**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Downloading https://www.nickelodeon.nl/episodes/ovmytb/spongebob-de-grill-is-weg-de-nachtburger-seizoen-seasonnumber-11-afl-24
This will be SE11E24
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.nickelodeon.nl/episodes/ovmytb/spongebob-de-grill-is-weg-de-nachtburger-seizoen-seasonnumber-11-afl-24', '--verbose', '--no-check-certificate', '--download-archive', '~/.Spongebob Squarepants', '-r', '5m', '-f', 'best', '-c', '-w', '--add-metadata', '-i', '--output', '/Volumes/GoogleDrive/My Drive/Media/Series/Spongebob Squarepants/Spongebob Squarepants - SE11E24.%(ext)s']
[debug] Loading archive file '/Users/niels/.Spongebob Squarepants'
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.7.3 (CPython) - Darwin-20.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[nick.de] spongebob-de-grill-is-weg-de-nachtburger-seizoen-seasonnumber-11-afl-24: Downloading webpage
[nick.de] 37ac4eb1-cd88-11e8-8764-70df2f866ace: Downloading JSON metadata
[nick.de] 37ac4eb1-cd88-11e8-8764-70df2f866ace: Downloading info
[nick.de] 4dbfba71-e933-11e8-a442-0e40cf2fc285: Extracting information
[nick.de] 4dbfba71-e933-11e8-a442-0e40cf2fc285: Downloading video urls
[nick.de] 4dbfba71-e933-11e8-a442-0e40cf2fc285: Downloading m3u8 information
[download] Downloading playlist: De grill is weg / De nachtburger
[nick.de] playlist De grill is weg / De nachtburger: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Invoking downloader on 'https://dlvrsvc.mtvnservices.com/api/playlist/gsp.mtviestor/intlod/won-intl/spongebob_squarepants/spongebob_squarepants_11/239_spongebob_squarepants_239/ABC742420/1/stream_1920x1080_4586235_1306594217.m3u8?tk=st=1612255637~exp=1612270037~acl=/api/playlist/gsp.mtviestor/intlod/won-intl/spongebob_squarepants/spongebob_squarepants_11/239_spongebob_squarepants_239/ABC742420/1/stream_1920x1080_4586235_1306594217.m3u8*~hmac=066b5bef4932e5fa9855d70436ca15cc4f39450f41492c764a884b264405bf64&account=intl.mtvi.com&cdn=ns1'
[download] /Volumes/GoogleDrive/My Drive/Media/Series/Spongebob Squarepants/Spongebob Squarepants - SE11E24.mp4 has already been downloaded
[download] 100% of 729.88MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:/Volumes/GoogleDrive/My Drive/Media/Series/Spongebob Squarepants/Spongebob Squarepants - SE11E24.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "/Volumes/GoogleDrive/My Drive/Media/Series/Spongebob Squarepants/Spongebob Squarepants - SE11E24.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Volumes/GoogleDrive/My Drive/Media/Series/Spongebob Squarepants/Spongebob Squarepants - SE11E24.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:/Volumes/GoogleDrive/My Drive/Media/Series/Spongebob Squarepants/Spongebob Squarepants - SE11E24.temp.mp4'
	ERROR: Conversion failed!
Traceback (most recent call last):
  File "/Users/niels/Library/Python/3.7/lib/python/site-packages/youtube_dlc/YoutubeDL.py", line 2150, in post_process
    files_to_delete, info = pp.run(info)
  File "/Users/niels/Library/Python/3.7/lib/python/site-packages/youtube_dlc/postprocessor/ffmpeg.py", line 618, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/Users/niels/Library/Python/3.7/lib/python/site-packages/youtube_dlc/postprocessor/ffmpeg.py", line 239, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/Users/niels/Library/Python/3.7/lib/python/site-packages/youtube_dlc/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dlc.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

## Description

```shell
python3 /Users/niels/Library/Python/3.9/lib/python/site-packages/youtube_dlc \
  "https://www.nickelodeon.nl/episodes/lgx2td/avatar-de-legende-van-aang-de-blinde-bandiet-seizoen-seasonnumber-2-afl-6" \
  --no-check-certificate \
  --download-archive "~/.avatar show" \
  -r 5m \
  -f best \
  -c \
  -w \
  --add-metadata \
  -i \
  --output "/Volumes/GoogleDrive/My Drive/Media/Series/avatar/avatar S02E06.%(ext)s"
```

Returns `Conversion Failed`.

**Comment by pukkandan** [comment]
youtube-dlc repo is moved to https://github.com/blackjack4494/yt-dlc after the DMCA takedown. However, it has also had no updates in over 2 months. You can use my fork [yt-dlp](https://github.com/pukkandan/yt-dlp) instead if you want. Anyway, you should report the issue in either of these to get any attention
