### ISSUE TITLE
Downloading youtube playlists doesn't work

### ISSUE THREAD

**Issue by jmakov** [blackjack4494/youtube-dlc#222]
## Checklist

- [x] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dlc version **2020.09.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
$ youtube-dlc --config-location youtube-dlc.conf --batch-file playlists.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--download-archive', 'archive.txt', '--output', '%(uploader)s/%(upload_date)s-%(title)s.%(ext)s', '--restrict-filenames', '--merge-output-format', 'mkv', '--ignore-errors', '--geo-bypass', '--write-description', '--write-info-json', '--write-annotations', '--no-call-home', '--write-auto-sub', '--all-subs']
[debug] Command-line args: ['--config-location', 'youtube-dlc.conf', '--batch-file', 'playlists.txt', '--verbose']
[debug] Batch file urls: ['_[SOME_URLS]_']
[debug] Loading archive file 'archive.txt'
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-70-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube:playlist] _SOME_URL_: Downloading webpage
ERROR: Unable to extract ytInitialData; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/toaster/.local/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/home/toaster/.local/lib/python3.8/site-packages/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/toaster/.local/lib/python3.8/site-packages/youtube_dlc/extractor/youtube.py", line 3042, in _real_extract
    has_videos, playlist = self._extract_playlist(playlist_id)
  File "/home/toaster/.local/lib/python3.8/site-packages/youtube_dlc/extractor/youtube.py", line 2994, in _extract_playlist
    next(self._entries(page, playlist_id))
  File "/home/toaster/.local/lib/python3.8/site-packages/youtube_dlc/extractor/youtube.py", line 341, in _entries
    data_json = self._parse_json(self._search_regex(self._INITIAL_DATA_RE, page, 'ytInitialData'), None)
  File "/home/toaster/.local/lib/python3.8/site-packages/youtube_dlc/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dlc.utils.RegexNotFoundError: Unable to extract ytInitialData; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description
The playlist is marked as "unlisted". Same result if playlist is set to "public".

$ youtube-dlc --version
2020.11.11-3

**Comment by llacb47** [comment]
this repo is abandoned. use youtube-dl or `https://github.com/pukkandan/yt-dlp`

**Comment by pukkandan** [comment]
@llab47, it's https://github.com/yt-dlp/yt-dlp now

**Comment by llacb47** [comment]
oops, sorry.
