### ISSUE TITLE
[Broken] AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by umbongodrink** [blackjack4494/youtube-dlc#223]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.09.16**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
$ youtube-dlc -v 'https://www.youtube.com/watch?v=sK7Mb_scMNA&t=317s&ab_channel=BrandonJamesGreer'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=sK7Mb_scMNA&t=317s&ab_channel=BrandonJamesGreer']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.8.8 (CPython) - Linux-4.15.0-123-generic-x86_64-with-glibc2.27
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] sK7Mb_scMNA: Downloading webpage
Traceback (most recent call last):
  File "/home/ladmin/.local/bin/youtube-dlc", line 11, in <module>
    sys.exit(main())
  File "/home/ladmin/.local/lib/python3.8/site-packages/youtube_dlc/__init__.py", line 487, in main
    _real_main(argv)
  File "/home/ladmin/.local/lib/python3.8/site-packages/youtube_dlc/__init__.py", line 477, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/ladmin/.local/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 2103, in download
    res = self.extract_info(
  File "/home/ladmin/.local/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/home/ladmin/.local/lib/python3.8/site-packages/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/ladmin/.local/lib/python3.8/site-packages/youtube_dlc/extractor/youtube.py", line 1940, in _real_extract
    args = ytplayer_config.get("args")
AttributeError: 'NoneType' object has no attribute 'get'

## Description

WRITE DESCRIPTION HERE

I have updated to the latest version of youtube-dlc, version 2020.11.11-3. 
If I try to download a certain URL as shown in my Verbose Log, I get the following error messages: 

  File "/home/ladmin/.local/bin/youtube-dlc", line 11, in <module>
    sys.exit(main())
  File "/home/ladmin/.local/lib/python3.8/site-packages/youtube_dlc/__init__.py", line 487, in main
    _real_main(argv)
  File "/home/ladmin/.local/lib/python3.8/site-packages/youtube_dlc/__init__.py", line 477, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/ladmin/.local/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 2103, in download
    res = self.extract_info(
  File "/home/ladmin/.local/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/home/ladmin/.local/lib/python3.8/site-packages/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/ladmin/.local/lib/python3.8/site-packages/youtube_dlc/extractor/youtube.py", line 1940, in _real_extract
    args = ytplayer_config.get("args")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by pukkandan** [comment]
youtube-dlc repo is moved to https://github.com/blackjack4494/yt-dlc after the DMCA takedown. However, it has also had no updates since last December. You can use my fork [yt-dlp](https://github.com/pukkandan/yt-dlp) instead if you want.

**Comment by umbongodrink** [comment]
Hi pukkandan, thanks a lot! I found it just before you replied to me, and it instantly worked. Thanks a lot for making your fork, brilliant work. Please continue and maintain it, many thanks indeed!!

**Comment by sleepingwheel** [comment]
Would be nice to see **yt-dlp** on brew, if possible?
