### ISSUE TITLE
[deezer]

### ISSUE THREAD

**Issue by blackjack4494** [blackjack4494/youtube-dlc#39]
https://github.com/ytdl-org/youtube-dl/pull/22074
@LucBerge

**Comment by LucBerge** [comment]
Full length song support, album, track and playlist extractor on branch deezer_uncipher : https://github.com/LucBerge/youtube-dl/tree/deezer_uncipher

**Comment by blackjack4494** [comment]
Thank you. Will have a look at it tho I don't have any deezer premium account.

**Comment by LucBerge** [comment]
You don't need any account to download the mp3

**Comment by blackjack4494** [comment]
As mentioned here https://github.com/blackjack4494/youtube-dlc/pull/46

I won't add the full uncipher yet.  
Also would be nice if someone with a premium account could test this or could lend their account.

**Comment by dimqua** [comment]
@LucBerge your version doesn't wok for me at the moment:
```
WARNING: "id" field is not a string - forcing string conversion, there is an error in extractor
ERROR: requested format not available
```

**Comment by LucBerge** [comment]
Could you please provide the full stacktrace using the -v option ?Le 28 sept. 2020 8:34 AM, dimqua <notifications@github.com> a écrit :
@LucBerge your version doesn't work for me at the moment:
WARNING: "id" field is not a string - forcing string conversion, there is an error in extractor
ERROR: requested format not available

**Comment by dimqua** [comment]
@LucBerge 
```
$ ./youtube-dl -v https://www.deezer.com/album/1004219 
[debug] System config: []
[debug] User config: [u'--write-sub', u'--write-auto-sub', u'--sub-lang', u'en,ru', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]', u'--merge-output-format', u'mkv']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.deezer.com/album/1004219']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.02
[debug] Python version 2.7.18rc1 (CPython) - Linux-5.4.0-44-generic-x86_64-with-neon-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 1004219: Requesting header
[redirect] Following redirect to https://www.deezer.com/us/album/1004219
[DeezerAlbum] 1004219: Downloading JSON metadata
[DeezerAlbum] 1004219: Downloading JSON metadata
[DeezerAlbum] 1004219: Downloading JSON metadata
[DeezerAlbum] 1004219: Downloading JSON metadata
[download] Downloading playlist: Ire Works
[DeezerAlbum] playlist Ire Works: Collected 13 video ids (downloading 13 of them)
[download] Downloading video 1 of 13
WARNING: "id" field is not a string - forcing string conversion, there is an error in extractor
ERROR: requested format not available
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1006, in process_ie_result
    extra_info=extra)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1634, in process_video_result
    expected=True)
ExtractorError: requested format not available
```

**Comment by dimqua** [comment]
NVM, I have figured it out. :-)
