### ISSUE TITLE
FrontendMasters and RayWenderlich not downloading

### ISSUE THREAD

**Issue by Viranchee** [blackjack4494/youtube-dlc#93]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running **youtube-dlc** version **2020.09.12**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-n', u'--verbose', u'https://frontendmasters.com/courses/serverless-functions/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.09.12
[debug] Python version 2.7.16 (CPython) - Darwin-20.1.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[FrontendMastersCourse] Downloading login page
[FrontendMastersCourse] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 529, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 433, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/frontendmasters.py", line 32, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/frontendmasters.py", line 70, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

FrontendMasters and RayWenderlich videos aren't getting downloaded

**Comment by blackjack4494** [comment]
Either your login details weren't correct (but I believe you checked those) or they changed their login routine/endpoint.
